from typing import Protocol


class Repository(Protocol):
    def load(self) -> object: ...

    def save(self, state: object) -> None: ...


class History(Protocol):
    def undo(self) -> object: ...

    def redo(self) -> object: ...
