# Config
# ***WARNING: The config is used for alot of logic operations. Adjusting it might break parts of the system. 

# Goal: link up all options from cli to the config. 

from config.schema import DEFINERS, AMOUNT_OF_BACKUPS, AMOUNT_OF_CONSECUTIVE_PREHUB_FAILS

def testin():
    transactions = [
        # --- Income ---
        {
            "name": "Salary January",
            "category": "income",
            "type": "I",
            "amount": 1450.00,
            "date": "01.01.2025",
        },
        {
            "name": "Salary February",
            "category": "income",
            "type": "I",
            "amount": 1450.00,
            "date": "01.02.2025",
        },
        {
            "name": "Salary March",
            "category": "income",
            "type": "I",
            "amount": 1450.00,
            "date": "01.03.2025",
        },
        {
            "name": "Salary April",
            "category": "income",
            "type": "I",
            "amount": 1450.00,
            "date": "01.04.2025",
        },
        {
            "name": "Salary May",
            "category": "income",
            "type": "I",
            "amount": 1450.00,
            "date": "01.05.2025",
        },
        {
            "name": "Salary June",
            "category": "income",
            "type": "I",
            "amount": 1450.00,
            "date": "01.06.2025",
        },
        {
            "name": "Salary July",
            "category": "income",
            "type": "I",
            "amount": 1450.00,
            "date": "01.07.2025",
        },
        {
            "name": "Salary August",
            "category": "income",
            "type": "I",
            "amount": 1450.00,
            "date": "01.08.2025",
        },
        {
            "name": "Salary September",
            "category": "income",
            "type": "I",
            "amount": 1450.00,
            "date": "01.09.2025",
        },
        {
            "name": "Salary October",
            "category": "income",
            "type": "I",
            "amount": 1450.00,
            "date": "01.10.2025",
        },
        {
            "name": "Salary November",
            "category": "income",
            "type": "I",
            "amount": 1450.00,
            "date": "01.11.2025",
        },
        {
            "name": "Salary December",
            "category": "income",
            "type": "I",
            "amount": 1450.00,
            "date": "01.12.2025",
        },
        {
            "name": "YouTube AdSense",
            "category": "income",
            "type": "I",
            "amount": 320.50,
            "date": "15.01.2025",
        },
        {
            "name": "YouTube AdSense",
            "category": "income",
            "type": "I",
            "amount": 287.15,
            "date": "15.02.2025",
        },
        {
            "name": "YouTube AdSense",
            "category": "income",
            "type": "I",
            "amount": 410.75,
            "date": "15.03.2025",
        },
        {
            "name": "Sponsorship Deal",
            "category": "income",
            "type": "I",
            "amount": 600.00,
            "date": "20.02.2025",
        },
        {
            "name": "Freelance Editing",
            "category": "income",
            "type": "I",
            "amount": 120.00,
            "date": "10.01.2025",
        },
        {
            "name": "Freelance Editing",
            "category": "income",
            "type": "I",
            "amount": 95.50,
            "date": "10.02.2025",
        },
        {
            "name": "Gift from Parents",
            "category": "income",
            "type": "I",
            "amount": 50.00,
            "date": "24.12.2024",
        },
        {
            "name": "Refund Amazon",
            "category": "income",
            "type": "I",
            "amount": 25.99,
            "date": "05.01.2025",
        },

        # --- Food ---
        {
            "name": "McDonalds",
            "category": "food",
            "type": "E",
            "amount": 11.99,
            "date": "03.01.2025",
        },
        {
            "name": "McDonalds",
            "category": "food",
            "type": "E",
            "amount": 8.49,
            "date": "08.01.2025",
        },
        {
            "name": "McDonalds",
            "category": "food",
            "type": "E",
            "amount": 9.99,
            "date": "12.01.2025",
        },
        {
            "name": "Groceries Lidl",
            "category": "food",
            "type": "E",
            "amount": 42.30,
            "date": "04.01.2025",
        },
        {
            "name": "Groceries Lidl",
            "category": "food",
            "type": "E",
            "amount": 15.80,
            "date": "11.01.2025",
        },
        {
            "name": "Groceries Lidl",
            "category": "food",
            "type": "E",
            "amount": 33.40,
            "date": "18.01.2025",
        },
        {
            "name": "Billa Groceries",
            "category": "food",
            "type": "E",
            "amount": 23.50,
            "date": "06.01.2025",
        },
        {
            "name": "Billa Groceries",
            "category": "food",
            "type": "E",
            "amount": 19.75,
            "date": "13.01.2025",
        },
        {
            "name": "Kebab Shop",
            "category": "food",
            "type": "E",
            "amount": 7.50,
            "date": "05.01.2025",
        },
        {
            "name": "Kebab Shop",
            "category": "food",
            "type": "E",
            "amount": 8.00,
            "date": "09.01.2025",
        },
        {
            "name": "Bakery Snack",
            "category": "food",
            "type": "E",
            "amount": 3.20,
            "date": "07.01.2025",
        },
        {
            "name": "Bakery Snack",
            "category": "food",
            "type": "E",
            "amount": 4.10,
            "date": "14.01.2025",
        },

        # --- Health ---
        {
            "name": "Protein Powder",
            "category": "health",
            "type": "E",
            "amount": 24.99,
            "date": "02.01.2025",
        },
        {
            "name": "Protein Powder",
            "category": "health",
            "type": "E",
            "amount": 24.99,
            "date": "02.02.2025",
        },
        {
            "name": "Protein Powder",
            "category": "health",
            "type": "E",
            "amount": 29.99,
            "date": "02.03.2025",
        },
        {
            "name": "Gym Membership",
            "category": "health",
            "type": "E",
            "amount": 29.99,
            "date": "01.01.2025",
        },
        {
            "name": "Gym Membership",
            "category": "health",
            "type": "E",
            "amount": 29.99,
            "date": "01.02.2025",
        },
        {
            "name": "Creatine",
            "category": "health",
            "type": "E",
            "amount": 14.50,
            "date": "05.02.2025",
        },
        {
            "name": "Multivitamins",
            "category": "health",
            "type": "E",
            "amount": 9.99,
            "date": "07.02.2025",
        },
        {
            "name": "Doctor Visit",
            "category": "health",
            "type": "E",
            "amount": 35.00,
            "date": "20.01.2025",
        },
        {
            "name": "Pharmacy Medicine",
            "category": "health",
            "type": "E",
            "amount": 12.75,
            "date": "22.01.2025",
        },

        # --- Transport ---
        {
            "name": "Train Ticket",
            "category": "transport",
            "type": "E",
            "amount": 3.00,
            "date": "03.01.2025",
        },
        {
            "name": "Train Ticket",
            "category": "transport",
            "type": "E",
            "amount": 3.00,
            "date": "04.01.2025",
        },
        {
            "name": "Train Ticket",
            "category": "transport",
            "type": "E",
            "amount": 3.00,
            "date": "05.01.2025",
        },
        {
            "name": "Monthly Pass",
            "category": "transport",
            "type": "E",
            "amount": 49.00,
            "date": "01.01.2025",
        },
        {
            "name": "Uber Ride",
            "category": "transport",
            "type": "E",
            "amount": 12.50,
            "date": "10.01.2025",
        },
        {
            "name": "Uber Ride",
            "category": "transport",
            "type": "E",
            "amount": 9.75,
            "date": "15.01.2025",
        },
        {
            "name": "Taxi Ride",
            "category": "transport",
            "type": "E",
            "amount": 18.00,
            "date": "20.01.2025",
        },
        {
            "name": "Scooter Rental",
            "category": "transport",
            "type": "E",
            "amount": 4.20,
            "date": "11.01.2025",
        },
        {
            "name": "Scooter Rental",
            "category": "transport",
            "type": "E",
            "amount": 6.10,
            "date": "16.01.2025",
        },

        # --- Subscriptions ---
        {
            "name": "Netflix Subscription",
            "category": "subscriptions",
            "type": "E",
            "amount": 12.99,
            "date": "05.01.2025",
        },
        {
            "name": "Netflix Subscription",
            "category": "subscriptions",
            "type": "E",
            "amount": 12.99,
            "date": "05.02.2025",
        },
        {
            "name": "Spotify Subscription",
            "category": "subscriptions",
            "type": "E",
            "amount": 9.99,
            "date": "07.01.2025",
        },
        {
            "name": "Spotify Subscription",
            "category": "subscriptions",
            "type": "E",
            "amount": 9.99,
            "date": "07.02.2025",
        },
        {
            "name": "YouTube Premium",
            "category": "subscriptions",
            "type": "E",
            "amount": 11.99,
            "date": "09.01.2025",
        },
        {
            "name": "iCloud Storage",
            "category": "subscriptions",
            "type": "E",
            "amount": 0.99,
            "date": "12.01.2025",
        },
        {
            "name": "Domain qluo.dev",
            "category": "subscriptions",
            "type": "E",
            "amount": 12.00,
            "date": "13.01.2025",
        },
        {
            "name": "Adobe Subscription",
            "category": "subscriptions",
            "type": "E",
            "amount": 24.99,
            "date": "14.01.2025",
        },

        # --- Self-care ---
        {
            "name": "DM Shampoo",
            "category": "selfcare",
            "type": "E",
            "amount": 6.45,
            "date": "02.01.2025",
        },
        {
            "name": "DM Shampoo",
            "category": "selfcare",
            "type": "E",
            "amount": 6.45,
            "date": "02.02.2025",
        },
        {
            "name": "Face Wash",
            "category": "selfcare",
            "type": "E",
            "amount": 5.99,
            "date": "06.01.2025",
        },
        {
            "name": "Moisturizer",
            "category": "selfcare",
            "type": "E",
            "amount": 7.49,
            "date": "08.01.2025",
        },
        {
            "name": "Toothpaste Colgate",
            "category": "selfcare",
            "type": "E",
            "amount": 2.89,
            "date": "09.01.2025",
        },
        {
            "name": "Toothbrush",
            "category": "selfcare",
            "type": "E",
            "amount": 3.49,
            "date": "10.01.2025",
        },
        {
            "name": "Haircut",
            "category": "selfcare",
            "type": "E",
            "amount": 18.00,
            "date": "15.01.2025",
        },
        {
            "name": "Barber Tip",
            "category": "selfcare",
            "type": "E",
            "amount": 2.00,
            "date": "15.01.2025",
        },

        # --- Entertainment ---
        {
            "name": "Cinema Ticket",
            "category": "entertainment",
            "type": "E",
            "amount": 10.50,
            "date": "17.01.2025",
        },
        {
            "name": "Cinema Ticket",
            "category": "entertainment",
            "type": "E",
            "amount": 10.50,
            "date": "24.01.2025",
        },
        {
            "name": "Cinema Snack Combo",
            "category": "entertainment",
            "type": "E",
            "amount": 7.99,
            "date": "24.01.2025",
        },
        {
            "name": "PC Game Steam",
            "category": "entertainment",
            "type": "E",
            "amount": 19.99,
            "date": "11.02.2025",
        },
        {
            "name": "PC Game Steam",
            "category": "entertainment",
            "type": "E",
            "amount": 39.99,
            "date": "18.03.2025",
        },
        {
            "name": "Robux Purchase",
            "category": "entertainment",
            "type": "E",
            "amount": 9.99,
            "date": "05.02.2025",
        },
        {
            "name": "Robux Purchase",
            "category": "entertainment",
            "type": "E",
            "amount": 19.99,
            "date": "12.02.2025",
        },
        {
            "name": "Concert Ticket",
            "category": "entertainment",
            "type": "E",
            "amount": 45.00,
            "date": "28.02.2025",
        },

        # --- Education / Projects ---
        {
            "name": "Udemy Course",
            "category": "education",
            "type": "E",
            "amount": 12.99,
            "date": "03.02.2025",
        },
        {
            "name": "Udemy Course",
            "category": "education",
            "type": "E",
            "amount": 9.99,
            "date": "10.02.2025",
        },
        {
            "name": "Programming Book",
            "category": "education",
            "type": "E",
            "amount": 29.99,
            "date": "12.02.2025",
        },
        {
            "name": "Electronics Components",
            "category": "education",
            "type": "E",
            "amount": 17.50,
            "date": "16.02.2025",
        },
        {
            "name": "Arduino Kit",
            "category": "education",
            "type": "E",
            "amount": 35.00,
            "date": "20.02.2025",
        },
        {
            "name": "Raspberry Pi",
            "category": "education",
            "type": "E",
            "amount": 55.00,
            "date": "24.02.2025",
        },
        {
            "name": "3D Printer Filament",
            "category": "education",
            "type": "E",
            "amount": 22.00,
            "date": "01.03.2025",
        },
        {
            "name": "3D Printer Filament",
            "category": "education",
            "type": "E",
            "amount": 22.00,
            "date": "15.03.2025",
        },

        # --- Housing / Home ---
        {
            "name": "Rent",
            "category": "housing",
            "type": "E",
            "amount": 550.00,
            "date": "01.01.2025",
        },
        {
            "name": "Electricity Bill",
            "category": "housing",
            "type": "E",
            "amount": 42.30,
            "date": "05.01.2025",
        },
        {
            "name": "Internet Bill",
            "category": "housing",
            "type": "E",
            "amount": 24.90,
            "date": "06.01.2025",
        },
        {
            "name": "Water Bill",
            "category": "housing",
            "type": "E",
            "amount": 15.20,
            "date": "07.01.2025",
        },
        {
            "name": "Cleaning Supplies",
            "category": "housing",
            "type": "E",
            "amount": 8.75,
            "date": "08.01.2025",
        },
        {
            "name": "Laundry Coins",
            "category": "housing",
            "type": "E",
            "amount": 4.00,
            "date": "09.01.2025",
        },
        {
            "name": "Desk Lamp",
            "category": "housing",
            "type": "E",
            "amount": 19.99,
            "date": "10.01.2025",
        },
        {
            "name": "Office Chair",
            "category": "housing",
            "type": "E",
            "amount": 89.99,
            "date": "11.01.2025",
        },

        # --- Other / Misc ---
        {
            "name": "Gift for Friend",
            "category": "other",
            "type": "E",
            "amount": 15.00,
            "date": "12.01.2025",
        },
        {
            "name": "Gift for Friend",
            "category": "other",
            "type": "E",
            "amount": 20.00,
            "date": "14.02.2025",
        },
        {
            "name": "Charity Donation",
            "category": "other",
            "type": "E",
            "amount": 10.00,
            "date": "18.01.2025",
        },
        {
            "name": "Bank Fee",
            "category": "other",
            "type": "E",
            "amount": 1.99,
            "date": "20.01.2025",
        },
        {
            "name": "ATM Withdrawal Fee",
            "category": "other",
            "type": "E",
            "amount": 2.50,
            "date": "22.01.2025",
        },
        {
            "name": "Phone Case",
            "category": "other",
            "type": "E",
            "amount": 9.99,
            "date": "23.01.2025",
        },
        {
            "name": "USB-C Cable",
            "category": "other",
            "type": "E",
            "amount": 6.99,
            "date": "24.01.2025",
        },
        {
            "name": "Power Bank",
            "category": "other",
            "type": "E",
            "amount": 24.99,
            "date": "25.01.2025",
        },
        {
            "name": "Screen Protector",
            "category": "other",
            "type": "E",
            "amount": 4.99,
            "date": "26.01.2025",
        },
        {
            "name": "Notebook",
            "category": "other",
            "type": "E",
            "amount": 2.50,
            "date": "27.01.2025",
        },
        {
            "name": "Pens Pack",
            "category": "other",
            "type": "E",
            "amount": 3.20,
            "date": "28.01.2025",
        },
    ]

    return transactions

def initvars():
    transactions = [] # totallist
    item = {} # one item
    definers = DEFINERS
    for i in range(len(definers)): item[definers[i][0]] = definers[i][1]
    count = 0 # amount of items, used for logic
    return(transactions, definers, item, count)

if __name__ == "__main__":
    """lstdict = testin()
    income, expense = sep_ie(lstdict)
    print(f"Income: {income}\nExpense: {expense}\n")
    print("\n")
    print(toti(income))
    print(tote(expense
    print(initvars()[2])"""
