# Calculation and summary formatting constants.

MONEY_FORMAT_MODE = "money"
INT_FORMAT_MODE = "int"
CURRENCY_SYMBOL = "\u20ac"

CALC_CONFIG = [
    ("Total Income", MONEY_FORMAT_MODE),
    ("Total Expense", MONEY_FORMAT_MODE),
    ("Net Balance", MONEY_FORMAT_MODE),
    ("Number of Transactions", INT_FORMAT_MODE),
    ("Average transaction amount", MONEY_FORMAT_MODE),
    ("Max transaction amount", MONEY_FORMAT_MODE),
    ("Min transaction amount", MONEY_FORMAT_MODE),
]

KEY_VALUE_PAIR_LABEL = "Key Value Pair"
TRANSACTIONS_ANALYZED_KEY = "Transactions Analyzed"

TOTAL_INCOME_LABEL = CALC_CONFIG[0][0]
TOTAL_EXPENSE_LABEL = CALC_CONFIG[1][0]
NET_BALANCE_LABEL = CALC_CONFIG[2][0]
NUMBER_OF_TRANSACTIONS_LABEL = CALC_CONFIG[3][0]

REQUIRED_CALCS = (
    NUMBER_OF_TRANSACTIONS_LABEL,
    TOTAL_INCOME_LABEL,
    TOTAL_EXPENSE_LABEL,
    NET_BALANCE_LABEL,
)

SUMMARY_TEMPLATE = {
    KEY_VALUE_PAIR_LABEL: "",
    TRANSACTIONS_ANALYZED_KEY: 0,
    TOTAL_INCOME_LABEL: 0.0,
    TOTAL_EXPENSE_LABEL: 0.0,
    NET_BALANCE_LABEL: 0.0,
}

SUMMARY_KEY_MAP = {
    NUMBER_OF_TRANSACTIONS_LABEL: TRANSACTIONS_ANALYZED_KEY,
    TOTAL_INCOME_LABEL: TOTAL_INCOME_LABEL,
    TOTAL_EXPENSE_LABEL: TOTAL_EXPENSE_LABEL,
    NET_BALANCE_LABEL: NET_BALANCE_LABEL,
}

SUMMARY_DISPLAY_KEYS = (TOTAL_INCOME_LABEL, TOTAL_EXPENSE_LABEL, NET_BALANCE_LABEL)

CATEGORY_OVERVIEW_TITLE = "Category Overview"
INCOME_EXPENSE_OVERVIEW_TITLE = "Income vs Expense"
